import { createSqliteStore } from '../shared/sqlite-store.js';
import { deterministicUuid } from '@franken/types';

export interface PlannerTask {
  id: string;
  title: string;
  deps: string[];
  status: 'pending' | 'done';
}

export interface PlannerDecomposeResult {
  planId: string;
  objective: string;
  tasks: PlannerTask[];
  provenance: 'generic-scaffold' | 'generated-decomposition';
  provenanceNote: string;
}

export interface PlannerValidateResult {
  verdict: 'valid' | 'invalid';
  issues: string[];
}

export type PlannerVisualizeResult =
  | { kind: 'found'; mermaid: string }
  | { kind: 'corrupt'; reason: string };

export interface PlannerAdapter {
  decompose(input: { objective: string; constraints?: string }): Promise<PlannerDecomposeResult>;
  visualize(planId: string): Promise<PlannerVisualizeResult | null>;
  validate(planId: string): Promise<PlannerValidateResult | null>;
}

interface StoredPlan {
  objective: string;
  constraints: string | null;
  tasks: PlannerTask[];
}

export function createPlannerAdapter(dbPath: string): PlannerAdapter {
  const store = createSqliteStore(dbPath);

  return {
    async decompose(input) {
      // Returns a scaffold DAG — not LLM-generated decomposition.
      // @franken/planner is a graph library (validate, visualize, cycle detection),
      // not a planning engine. Real decomposition requires an LLM, and since this
      // MCP tool is called BY an LLM (Claude Code), injecting a second LLM call
      // here would be circular. The caller refines this scaffold as needed.
      const planId = deterministicUuid('packages/franken-mcp-suite/src/adapters/planner-adapter.ts').slice(0, 8);
      const tasks: PlannerTask[] = [
        { id: 't1', title: `Analyze requirements for: ${input.objective}`, deps: [], status: 'pending' },
        { id: 't2', title: 'Design solution architecture', deps: ['t1'], status: 'pending' },
        { id: 't3', title: 'Write failing tests', deps: ['t2'], status: 'pending' },
        { id: 't4', title: 'Implement solution', deps: ['t3'], status: 'pending' },
        { id: 't5', title: 'Verify tests pass', deps: ['t4'], status: 'pending' },
        { id: 't6', title: 'Review and refine', deps: ['t5'], status: 'pending' },
      ];

      const provenance = 'generic-scaffold' as const;
      const provenanceNote = 'Generated by the built-in generic scaffold, not by an objective-specific planner.';
      const stored: StoredPlan = {
        objective: input.objective,
        constraints: input.constraints ?? null,
        tasks,
      };

      store.db.prepare(`
        INSERT INTO plans (id, objective, dag, status) VALUES (?, ?, ?, 'pending')
      `).run(planId, input.objective, JSON.stringify(stored));

      return { planId, objective: input.objective, tasks, provenance, provenanceNote };
    },

    async visualize(planId) {
      const loaded = loadPlan(planId);
      if (!loaded) {
        return null;
      }
      if (loaded.kind === 'corrupt') {
        return loaded;
      }

      const plan = loaded.plan;
      return { kind: 'found', mermaid: renderMermaid(plan.tasks) };
    },

    async validate(planId) {
      const loaded = loadPlan(planId);
      if (!loaded) {
        return null;
      }
      if (loaded.kind === 'corrupt') {
        return {
          verdict: 'invalid',
          issues: [`Plan data is invalid/corrupt: ${loaded.reason}`],
        };
      }

      const plan = loaded.plan;
      const issues: string[] = [];
      const taskIds = new Set(plan.tasks.map((task) => task.id));

      for (const task of plan.tasks) {
        for (const dep of task.deps) {
          if (!taskIds.has(dep)) {
            issues.push(`Task ${task.id} depends on unknown task: ${dep}`);
          }
        }
      }

      if (plan.tasks.length === 0) {
        issues.push('Plan has no tasks');
      }

      if (issues.length === 0) {
        if (hasCycle(plan.tasks)) {
          issues.push('Cycle detected in task dependencies');
        }
      }

      return {
        verdict: issues.length === 0 ? 'valid' : 'invalid',
        issues,
      };
    },
  };

  function loadPlan(planId: string): { kind: 'found'; plan: StoredPlan } | { kind: 'corrupt'; reason: string } | null {
    const row = store.db.prepare('SELECT dag FROM plans WHERE id = ?').get(planId) as { dag: string } | undefined;
    if (!row) {
      return null;
    }

    return decodeStoredPlan(row.dag);
  }
}

function decodeStoredPlan(rawDag: string): { kind: 'found'; plan: StoredPlan } | { kind: 'corrupt'; reason: string } {
  let parsed: unknown;
  try {
    parsed = JSON.parse(rawDag);
  } catch (error) {
    return { kind: 'corrupt', reason: `stored plan DAG is not valid JSON: ${error instanceof Error ? error.message : String(error)}` };
  }

  if (!isRecord(parsed)) {
    return { kind: 'corrupt', reason: 'stored plan DAG must be an object' };
  }

  if (typeof parsed.objective !== 'string') {
    return { kind: 'corrupt', reason: 'stored plan DAG objective must be a string' };
  }
  if (parsed.constraints !== null && parsed.constraints !== undefined && typeof parsed.constraints !== 'string') {
    return { kind: 'corrupt', reason: 'stored plan DAG constraints must be a string or null' };
  }
  if (!Array.isArray(parsed.tasks)) {
    return { kind: 'corrupt', reason: 'stored plan DAG tasks must be an array' };
  }

  const tasks: PlannerTask[] = [];
  const taskIds = new Set<string>();
  for (const [index, task] of parsed.tasks.entries()) {
    if (!isRecord(task)) {
      return { kind: 'corrupt', reason: `stored plan DAG tasks[${index}] must be an object` };
    }
    if (typeof task.id !== 'string' || task.id.length === 0) {
      return { kind: 'corrupt', reason: `stored plan DAG tasks[${index}].id must be a non-empty string` };
    }
    if (taskIds.has(task.id)) {
      return { kind: 'corrupt', reason: `stored plan DAG contains duplicate task id: ${task.id}` };
    }
    if (typeof task.title !== 'string') {
      return { kind: 'corrupt', reason: `stored plan DAG tasks[${index}].title must be a string` };
    }
    if (!Array.isArray(task.deps) || !task.deps.every((dep) => typeof dep === 'string')) {
      return { kind: 'corrupt', reason: `stored plan DAG tasks[${index}].deps must be an array of strings` };
    }
    if (task.status !== 'pending' && task.status !== 'done') {
      return { kind: 'corrupt', reason: `stored plan DAG tasks[${index}].status must be pending or done` };
    }

    taskIds.add(task.id);
    tasks.push({
      id: task.id,
      title: task.title,
      deps: task.deps,
      status: task.status,
    });
  }

  return {
    kind: 'found',
    plan: {
      objective: parsed.objective,
      constraints: parsed.constraints ?? null,
      tasks,
    },
  };
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function renderMermaid(tasks: PlannerTask[]): string {
  const mermaidLines = ['graph TD'];
  for (const task of tasks) {
    mermaidLines.push(`  ${task.id}["${task.title}"]`);
    for (const dep of task.deps) {
      mermaidLines.push(`  ${dep} --> ${task.id}`);
    }
  }

  return mermaidLines.join('\n');
}

function hasCycle(tasks: PlannerTask[]): boolean {
  const byId = new Map(tasks.map((task) => [task.id, task]));
  const visiting = new Set<string>();
  const visited = new Set<string>();

  function visit(taskId: string): boolean {
    if (visiting.has(taskId)) {
      return true;
    }
    if (visited.has(taskId)) {
      return false;
    }
    const task = byId.get(taskId);
    if (!task) {
      return false;
    }

    visiting.add(taskId);
    for (const dep of task.deps) {
      if (visit(dep)) {
        return true;
      }
    }
    visiting.delete(taskId);
    visited.add(taskId);
    return false;
  }

  return tasks.some((task) => visit(task.id));
}
