import { createSqliteStore } from '../shared/sqlite-store.js';
import { randomUUID } from 'node:crypto';
import { z } from 'zod';

export interface PlannerTask {
  id: string;
  title: string;
  deps: string[];
  status: 'pending' | 'done';
}

export interface PlannerDecomposeResult {
  planId: string;
  objective: string;
  tasks: PlannerTask[];
  provenance: 'generic-scaffold' | 'generated-decomposition';
  provenanceNote: string;
}

export interface PlannerValidateResult {
  verdict: 'valid' | 'invalid';
  issues: string[];
}

export type PlannerVisualizeResult =
  | { kind: 'found'; mermaid: string }
  | { kind: 'corrupt'; reason: string };

export interface PlannerAdapter {
  decompose(input: { objective: string; constraints?: string }): Promise<PlannerDecomposeResult>;
  visualize(planId: string): Promise<PlannerVisualizeResult | null>;
  validate(planId: string): Promise<PlannerValidateResult | null>;
}

interface StoredPlan {
  objective: string;
  constraints: string | null;
  tasks: PlannerTask[];
}

export function createPlannerAdapter(dbPath: string): PlannerAdapter {
  const store = createSqliteStore(dbPath);

  return {
    async decompose(input) {
      // Returns a scaffold DAG — not LLM-generated decomposition.
      // @franken/planner is a graph library (validate, visualize, cycle detection),
      // not a planning engine. Real decomposition requires an LLM, and since this
      // MCP tool is called BY an LLM (Claude Code), injecting a second LLM call
      // here would be circular. The caller refines this scaffold as needed.
      const planId = createUniquePlanId(store);
      const tasks: PlannerTask[] = [
        { id: 't1', title: `Analyze requirements for: ${input.objective}`, deps: [], status: 'pending' },
        { id: 't2', title: 'Design solution architecture', deps: ['t1'], status: 'pending' },
        { id: 't3', title: 'Write failing tests', deps: ['t2'], status: 'pending' },
        { id: 't4', title: 'Implement solution', deps: ['t3'], status: 'pending' },
        { id: 't5', title: 'Verify tests pass', deps: ['t4'], status: 'pending' },
        { id: 't6', title: 'Review and refine', deps: ['t5'], status: 'pending' },
      ];

      const provenance = 'generic-scaffold' as const;
      const provenanceNote = 'Generated by the built-in generic scaffold, not by an objective-specific planner.';
      const stored: StoredPlan = {
        objective: input.objective,
        constraints: input.constraints ?? null,
        tasks,
      };

      store.db.prepare(`
        INSERT INTO plans (id, objective, dag, status) VALUES (?, ?, ?, 'pending')
      `).run(planId, input.objective, JSON.stringify(stored));

      return { planId, objective: input.objective, tasks, provenance, provenanceNote };
    },

    async visualize(planId) {
      const loaded = loadPlan(planId);
      if (!loaded) {
        return null;
      }
      if (loaded.kind === 'corrupt') {
        return loaded;
      }

      const plan = loaded.plan;
      return { kind: 'found', mermaid: renderMermaid(plan.tasks) };
    },

    async validate(planId) {
      const loaded = loadPlan(planId);
      if (!loaded) {
        return null;
      }
      if (loaded.kind === 'corrupt') {
        return {
          verdict: 'invalid',
          issues: [`Plan data is invalid/corrupt: ${loaded.reason}`],
        };
      }

      const plan = loaded.plan;
      const issues: string[] = [];
      const taskIds = new Set(plan.tasks.map((task) => task.id));

      for (const task of plan.tasks) {
        for (const dep of task.deps) {
          if (!taskIds.has(dep)) {
            issues.push(`Task ${task.id} depends on unknown task: ${dep}`);
          }
        }
      }

      if (plan.tasks.length === 0) {
        issues.push('Plan has no tasks');
      }

      if (issues.length === 0) {
        if (hasCycle(plan.tasks)) {
          issues.push('Cycle detected in task dependencies');
        }
      }

      return {
        verdict: issues.length === 0 ? 'valid' : 'invalid',
        issues,
      };
    },
  };

  function loadPlan(planId: string): { kind: 'found'; plan: StoredPlan } | { kind: 'corrupt'; reason: string } | null {
    const row = store.db.prepare('SELECT dag FROM plans WHERE id = ?').get(planId) as { dag: string } | undefined;
    if (!row) {
      return null;
    }

    return decodeStoredPlan(row.dag);
  }
}

function createUniquePlanId(store: ReturnType<typeof createSqliteStore>): string {
  for (let attempt = 0; attempt < 5; attempt++) {
    const planId = randomUUID().slice(0, 8);
    const existing = store.db.prepare('SELECT 1 FROM plans WHERE id = ?').get(planId);
    if (!existing) {
      return planId;
    }
  }

  return randomUUID();
}

// Untrusted input: `rawDag` is read back from SQLite storage, which may have
// been written by an older schema version, hand-edited, or tampered with by
// a compromised process. It is validated against `storedPlanSchema` (shape
// and type correctness) and scanned for prototype-pollution-shaped keys
// before any field is trusted, and every rejection is a deterministic
// "corrupt" result rather than a thrown exception — callers never see an
// uncaught error from malformed storage.
const UNSAFE_OBJECT_KEYS = new Set(['__proto__', 'constructor', 'prototype']);

/**
 * Recursively scans an already-parsed JSON value for own keys named
 * `__proto__`, `constructor`, or `prototype` at any depth. These keys are
 * broadly safe as JSON.parse output (JSON.parse never mutates the real
 * prototype chain), but rejecting them defensively — mirroring the
 * @franken/brain working-memory hydration guard — protects any downstream
 * consumer that might later merge or spread this value unsafely.
 */
function findUnsafeObjectKey(value: unknown): string | null {
  if (Array.isArray(value)) {
    for (const item of value) {
      const found = findUnsafeObjectKey(item);
      if (found !== null) {
        return found;
      }
    }
    return null;
  }
  if (isRecord(value)) {
    for (const key of Object.keys(value)) {
      if (UNSAFE_OBJECT_KEYS.has(key)) {
        return key;
      }
      const found = findUnsafeObjectKey(value[key]);
      if (found !== null) {
        return found;
      }
    }
  }
  return null;
}

const plannerTaskSchema = z
  .object({
    id: z.string().min(1),
    title: z.string(),
    deps: z.array(z.string()),
    status: z.enum(['pending', 'done']),
  })
  .strict();

const storedPlanSchema = z
  .object({
    objective: z.string(),
    constraints: z.string().nullable().optional(),
    tasks: z.array(plannerTaskSchema),
  })
  .strict()
  .superRefine((plan, ctx) => {
    const seenIds = new Set<string>();
    plan.tasks.forEach((task, index) => {
      if (seenIds.has(task.id)) {
        ctx.addIssue({
          code: 'custom',
          message: `duplicate:${task.id}`,
          path: ['tasks', index, 'id'],
        });
      } else {
        seenIds.add(task.id);
      }
    });
  });

interface StoredPlanIssueLike {
  code: string;
  path: ReadonlyArray<string | number>;
  message: string;
  keys?: string[];
}

function formatZodPath(path: ReadonlyArray<string | number>): string {
  let out = '';
  for (const segment of path) {
    if (typeof segment === 'number') {
      out += `[${segment}]`;
    } else {
      out += out.length > 0 ? `.${segment}` : segment;
    }
  }
  return out;
}

function describeStoredPlanIssue(issue: StoredPlanIssueLike): string {
  if (issue.code === 'custom' && issue.message.startsWith('duplicate:')) {
    return `stored plan DAG contains duplicate task id: ${issue.message.slice('duplicate:'.length)}`;
  }

  const path = formatZodPath(issue.path);

  if (issue.code === 'unrecognized_keys') {
    const keys = issue.keys?.join(', ') ?? '';
    return `stored plan DAG${path ? ` ${path}` : ''} contains unexpected field(s): ${keys}`;
  }
  if (path === '') {
    return 'stored plan DAG must be an object';
  }
  if (path === 'objective') {
    return 'stored plan DAG objective must be a string';
  }
  if (path === 'constraints') {
    return 'stored plan DAG constraints must be a string or null';
  }
  if (path === 'tasks') {
    return 'stored plan DAG tasks must be an array';
  }

  const taskObjectMatch = /^tasks\[(\d+)\]$/.exec(path);
  if (taskObjectMatch) {
    return `stored plan DAG tasks[${taskObjectMatch[1]}] must be an object`;
  }

  const taskFieldMatch = /^tasks\[(\d+)\]\.(\w+)/.exec(path);
  if (taskFieldMatch) {
    const [, index, field] = taskFieldMatch;
    switch (field) {
      case 'id':
        return `stored plan DAG tasks[${index}].id must be a non-empty string`;
      case 'title':
        return `stored plan DAG tasks[${index}].title must be a string`;
      case 'deps':
        return `stored plan DAG tasks[${index}].deps must be an array of strings`;
      case 'status':
        return `stored plan DAG tasks[${index}].status must be pending or done`;
    }
  }

  return `stored plan DAG${path ? ` ${path}` : ''} is invalid: ${issue.message}`;
}

function decodeStoredPlan(rawDag: string): { kind: 'found'; plan: StoredPlan } | { kind: 'corrupt'; reason: string } {
  let parsed: unknown;
  try {
    parsed = JSON.parse(rawDag);
  } catch (error) {
    const reason = `stored plan DAG is not valid JSON: ${error instanceof Error ? error.message : String(error)}`;
    console.error(`[planner-adapter] failed to parse stored plan DAG; aborting: ${reason}`);
    return { kind: 'corrupt', reason };
  }

  const unsafeKey = findUnsafeObjectKey(parsed);
  if (unsafeKey !== null) {
    const reason = `stored plan DAG contains unsafe key "${unsafeKey}" and was rejected`;
    console.error(`[planner-adapter] rejected malformed stored plan DAG; aborting: ${reason}`);
    return { kind: 'corrupt', reason };
  }

  const result = storedPlanSchema.safeParse(parsed);
  if (!result.success) {
    const reason = describeStoredPlanIssue(result.error.issues[0] as StoredPlanIssueLike);
    console.error(`[planner-adapter] rejected malformed stored plan DAG; aborting: ${reason}`);
    return { kind: 'corrupt', reason };
  }

  return {
    kind: 'found',
    plan: {
      objective: result.data.objective,
      constraints: result.data.constraints ?? null,
      tasks: result.data.tasks,
    },
  };
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function renderMermaid(tasks: PlannerTask[]): string {
  const mermaidLines = ['graph TD'];
  for (const task of tasks) {
    mermaidLines.push(`  ${task.id}["${task.title}"]`);
    for (const dep of task.deps) {
      mermaidLines.push(`  ${dep} --> ${task.id}`);
    }
  }

  return mermaidLines.join('\n');
}

function hasCycle(tasks: PlannerTask[]): boolean {
  const byId = new Map(tasks.map((task) => [task.id, task]));
  const visiting = new Set<string>();
  const visited = new Set<string>();

  function visit(taskId: string): boolean {
    if (visiting.has(taskId)) {
      return true;
    }
    if (visited.has(taskId)) {
      return false;
    }
    const task = byId.get(taskId);
    if (!task) {
      return false;
    }

    visiting.add(taskId);
    for (const dep of task.deps) {
      if (visit(dep)) {
        return true;
      }
    }
    visiting.delete(taskId);
    visited.add(taskId);
    return false;
  }

  return tasks.some((task) => visit(task.id));
}
