export const TEST_TOKEN_BUDGET = 100_000;

export const TOKEN_OVERRUN_INPUT_TOKENS = 80_000;
export const TOKEN_OVERRUN_OUTPUT_TOKENS = 30_000;
export const TOKEN_OVERRUN_TOTAL_TOKENS = TOKEN_OVERRUN_INPUT_TOKENS + TOKEN_OVERRUN_OUTPUT_TOKENS;
