import { describe, it, expect, vi } from 'vitest';
import { createPlannerServer } from './planner.js';

describe('Planner Server', () => {
  it('exposes 3 tools', () => {
    const server = createPlannerServer({
      planner: {
        decompose: vi.fn(),
        visualize: vi.fn(),
        validate: vi.fn(),
      },
    });

    const names = server.tools.map((t) => t.name);
    expect(names).toEqual(['fbeast_plan_decompose', 'fbeast_plan_status', 'fbeast_plan_validate']);
  });

  it('delegates decompose and validate to the planner adapter', async () => {
    const planner = {
      decompose: vi.fn().mockResolvedValue({
        planId: 'p1',
        objective: 'ship',
        tasks: [{ id: 't1', title: 'wire adapter', deps: [], status: 'pending' }],
        provenance: 'generic-scaffold',
        provenanceNote: 'Generated by the built-in generic scaffold, not by an objective-specific planner.',
      }),
      visualize: vi.fn().mockResolvedValue({ kind: 'found', mermaid: 'graph TD\n  t1["wire adapter"]' }),
      validate: vi.fn().mockResolvedValue({ verdict: 'valid', issues: [] }),
    };

    const server = createPlannerServer({ planner });
    const decomposeTool = server.tools.find((t) => t.name === 'fbeast_plan_decompose')!;
    const visualizeTool = server.tools.find((t) => t.name === 'fbeast_plan_status')!;
    const validateTool = server.tools.find((t) => t.name === 'fbeast_plan_validate')!;

    const decomposeResult = await decomposeTool.handler({ objective: 'ship', constraints: 'small PRs' });
    expect(planner.decompose).toHaveBeenCalledWith({ objective: 'ship', constraints: 'small PRs' });
    const decomposeText = decomposeResult.content[0]!.text;
    expect(decomposeText).toContain('p1');
    expect(decomposeText).toContain('**Provenance:** generic-scaffold');
    expect(decomposeText).toContain('not by an objective-specific planner');
    expect(decomposeText).toContain('fbeast_plan_status');
    expect(decomposeText).not.toContain('fbeast_plan_visualize');
    const registeredToolNames = new Set(server.tools.map((t) => t.name));
    const mentionedPlannerTools = [...decomposeText.matchAll(/fbeast_plan_[a-z_]+/g)].map((match) => match[0]);
    expect(mentionedPlannerTools.length).toBeGreaterThan(0);
    for (const toolName of mentionedPlannerTools) {
      expect(registeredToolNames.has(toolName)).toBe(true);
    }

    const visualizeResult = await visualizeTool.handler({ planId: 'p1' });
    expect(planner.visualize).toHaveBeenCalledWith('p1');
    expect(visualizeResult.content[0]!.text).toContain('graph TD');

    const validateResult = await validateTool.handler({ planId: 'p1' });
    expect(planner.validate).toHaveBeenCalledWith('p1');
    expect(validateResult.content[0]!.text).toContain('valid');
  });

  it('returns tool errors for corrupt stored plan status results', async () => {
    const planner = {
      decompose: vi.fn(),
      visualize: vi.fn().mockResolvedValue({ kind: 'corrupt', reason: 'stored plan DAG tasks must be an array' }),
      validate: vi.fn(),
    };

    const server = createPlannerServer({ planner });
    const visualizeTool = server.tools.find((t) => t.name === 'fbeast_plan_status')!;

    const result = await visualizeTool.handler({ planId: 'p1' });

    expect(result.isError).toBe(true);
    expect(result.content[0]!.text).toMatch(/invalid\/corrupt.*tasks must be an array/i);
  });
});
